### ISSUE TITLE
FC with latest git version

### ISSUE THREAD

**Issue by ogr3** [koush/Superuser#11]
I built from source (including latest commit 6b8c7a16a2)  and got an FC:

I/ActivityManager(  389): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.koushikdutta.superuser/.MainActivity bnds=[190,850][360,1050]} from pid 711
I/ActivityManager(  389): Start proc com.koushikdutta.superuser for activity com.koushikdutta.superuser/.MainActivity: pid=2595 uid=10143 gids={50143, 1028}
E/AndroidRuntime( 2595): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.koushikdutta.superuser/com.koushikdutta.superuser.MainActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x7f060014
E/AndroidRuntime( 2595):    at com.koushikdutta.superuser.MainActivity.onCreate(MainActivity.java:72)
W/ActivityManager(  389):   Force finishing activity com.koushikdutta.superuser/.MainActivity
W/ActivityManager(  389): Activity pause timeout for ActivityRecord{426c9a08 u0 com.koushikdutta.superuser/.MainActivity}
I/ActivityManager(  389): Process com.koushikdutta.superuser (pid 2595) has died

**Comment by koush** [comment]
which phone and os version?

**Comment by koush** [comment]
also update Widgets dependency if you havent

**Comment by ogr3** [comment]
Widgets were updated at the same time (wouldn't build otherwise) 

Device is galaxy nexus stock 4.2.2

**Comment by koush** [comment]
Try refreshing both projects in eclipse and cleaning then building. I am assuming you are using eclipse.

I just repulled and everything is working fine here on my nexus. It seems you have a resource issue, which is usually indicative of the project not being refreshed in eclipse or something.

**Comment by ogr3** [comment]
Using ant from command line with android-sdk and ndk installed via homebrew (using a Mac). 

Did a ant clean on Superuser, maybe need to do it on Widgets as well. Will try.

**Comment by koush** [comment]
Oh, you're using ant. I've had very poor results with using ant on my other apps (missing classes in final apk, etc).

I'm not sure what is up with it, but it is not something I've thoroughly tested admittedly. It "builds" but I don't know if it actually works.

**Comment by koush** [comment]
Yeah, an ant clean may help

**Comment by koush** [comment]
Also, running

ant zip

will create a recovery zip

**Comment by ogr3** [comment]
Yeah, I've used ant zip to create the file.

Just tried a fresh pull and built on a windows machine instead (using cygwin as a shell ;)) And this zip works. Probably something not cleaning the Widgets project correctly when doing ant clean on Superuser.

I will try it on the Mac again tomorrow, but this bug can probably be closed.
