### ISSUE TITLE
Feature request: OTA survival 

### ISSUE THREAD

**Issue by ogr3** [koush/Superuser#115]
Voodoo OTA rootkeeper already does this: https://github.com/project-voodoo/ota-rootkeeper-app

What would be nice is an implementation where Superuser silently keeps a copy of it's su binary in another place than /system/xbin. After an OTA the su binary will be stripped of it's execute bit. 

Could you then use the extra copy of su to re-root?

Then Superuser would be self contained and could detect a loss of root due to OTA and fix it.

Since it's a copy of Superuser's su, the version och checksum can be checked to see that the copy hasn't been tampered with.

**Comment by sparkym3** [comment]
It definitely could do that, but I would suggest a dynamic strategy to help resolve the issue around official ROM makers trying to strip out the su and the backups upon update. If the location is hard coded for the backup, any ROM maker could easily look that up and cause it to be wiped out on update.  If we were to have a default location but also allow for that location to be selected (or potentially a double backup in case the default location fails), it would allow for people to use an unknown location, to the official ROM makers, and provide a greater possibility that it will persist. (Personally I use a double backup method with voodoo and a custom copy I make, but that is annoying always having to make a manual update to my custom copy).

Of course, this would have to have some kind of check to verify that the chosen save location allows for all of the proper permission bits to be set.
