### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Sarkie** [koush/Superuser#130]
Running su command causes a segmentation fault.

I have a Nexus One, running MIUI 2.3.0.

I have managed to build the source, using printf and fflush doesn't show where it is dying, so I have put a return statement before each method call to see where it is dying and I'll go and remove each one to see what line/method call where it is dying.

My C isn't great, haven't done it in a fair few years, so if there's anything I can do to help make this a better issue report, please tell me.

Cheers.

**Comment by koush** [comment]
hm i have not tested on a nexus one, I suspect it may be an ARM/thumb/neon issue. I'll rebuild as ARM only and send you a binary.

**Comment by ogr3** [comment]
I've ran Superuser succesfully on my HTC Desire (s-off, with Oxygen 2.3.2 ROM), so 'arm-wise' it should run fine on Nexus One. I haven't tried a home-built version, only the one from Google play.

**Comment by Sarkie** [comment]
@koush Can you see my email? Is the build on http://download.clockworkmod.com/superuser/superuser.zip always the latest one?

@ogr3 I am think its a MIUI thing since not many people have complained about it.

**Comment by koush** [comment]
@Sarkie yes, that is always the latest. Can you paste comments relevant to the issue here, versus email?

**Comment by Sarkie** [comment]
@koush Oh ok, the latest one still blew up. I'm currently doing the printfs.

I meant regarding sending me a different build instead of putting my email on here.

**Comment by Sarkie** [comment]
It is dying on

dballow = database_check(&ctx);

Line 829 in su.c 

Which is calling db.c but I am now too busy to look where in db.c, database_check, I'll look later if you have no idea why/where its dying.

I changed the following switch statement to switch(ALLOW) to allow everything through for now and everything works correctly for my phone now.

Cheers.

**Comment by Sarkie** [comment]
@koush It is dying on

 int ret = sqlite3_open_v2(ctx->user.database_path, &db, SQLITE_OPEN_READONLY, NULL);

in db.c, you are using the latest sqlite I can see, and it works on Desire, so it must be miui? The database file is there and is valid, I adb pull'ed it to make sure. Hmm.

**Comment by koush** [comment]
can you check the value of ctx->user.database_path

make sure it is populated, etc.

I assume you're using the sqlite included with Superuser, vs another one? How are you building it? Embedded or standalone app?

**Comment by Sarkie** [comment]
Yeah I printf'd it, its pointing to the correct place in \data\ I adb'd it to my local drive and opened it up, it was valid, just empty.

Yeah I'm using yours, just going into Superuser and ndk-building it, I think put it inside a update.zip, booting to recovery to install it.

**Comment by koush** [comment]
That's weird. I have no idea what could be wrong.

You could try putting an older version of SQLite in I guess? Maybe there's a regression in the lib.

My other thought is that it does not support some CPU instruction generated by the NDK. But the Nexus One is ARMv7 with Neon support.

**Comment by Sarkie** [comment]
Yeah, that was the plan but I can't figure out where to get an older version of it amalgamated, can you?

Yeah, could be but the HTC Desire is the same CPU, so ogr3's would've died too, I don't know anyone else with a Nexus One to test it.

I was going to try and get ndk-gdb working, to see if I can find where it is actually blowing up. :(

**Comment by koush** [comment]
@Sarkie try using android's official sqlite3 instead of the one I packaged. Can grab that off AOSP or CM. I used the official website one, which may be more recent.

**Comment by Sarkie** [comment]
I've just tried using CM and AOSP (with the one from Gingerbread and still the same, so it might be the ndk compilers? I was going to get an old version and see if it compiles correctly?

Annoying.

**Comment by Sarkie** [comment]
We have a winner.

Looking at : http://stackoverflow.com/questions/5523067/sqlite-with-android-ndk

He mentioned about the libsqlite.so included, so I'm thinking that the one on my device or the _jni one is bugged or too old and the lib needs to be in the correct directory to be picked up over the one in /system/lib but since its su should it be in /var or /usr somewhere?

I took a different build of miui from miuiandroid.com instead of miui.us and installed over the top of my rom and now Superuser works! :)

**Comment by koush** [comment]
Superuser uses a statically linked sqlite, why would the libsqlite.so on device matter?

**Comment by Sarkie** [comment]
Ah ok, I haven't got a clue then. I'm guessing my ROM was fubar'ed so installing over the top fixed whatever was corrupted...
