### ISSUE TITLE
CyanogenMod Gerrit not configured OK

### ISSUE THREAD

**Issue by ogr3** [koush/Superuser#134]
As soon as someone commits a patch to the translations according to the requested way CyanogenMod Gerrit croaks:

fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sh: 1: cd: can't cd to Superuser

Where do you file a bug report for the CyanogenMod build environment?

**Comment by koush** [comment]
Not sure. Working fine here. I doubt it is the build environment. We have thousands of contributors that don't have this problem.

Link to the instructions you found?

**Comment by ogr3** [comment]
The log was from Jenkins, but it looks like translations are being merged now, so I guess they fixed it.
