### ISSUE TITLE
Incorrect su binary updated on x86 system.

### ISSUE THREAD

**Issue by avdimdv** [koush/Superuser#138]
On Motorola RAZR i updating su binary after choosing simply install (not recovery) lead to placing arm version of su in /system/xbin.
I was previously on ChainsDD superuser and install version 1.0.1.5 from Play Store. First launch obviously wanted to update binary but did it wrong way. Hopefully I had some su binary backed up on the device and was able to restore root through adb shell. Without this I would loose root.

EDIT. I mean I placed your x86 su binary taken from APK, place in proper place, chmod it and everything is working since then.

**Comment by avdimdv** [comment]
Look into source code. Here is what cat /proc/cpuinfo reported on my phone

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 39
model name      : Intel(R) Atom(TM) CPU Z2480  @ 2.00GHz
stepping        : 2
cpu MHz         : 600.000
cache size      : 512 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fdiv_bug        : no
hlt_bug         : no
f00f_bug        : no
coma_bug        : no
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx constant_tsc arch_perfmon
 pebs bts nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 xtpr pdcm movbe lahf_lm arat dts tpr_shadow vnmi flexpriority
bogomips        : 3993.60
clflush size    : 64
cache_alignment : 64
address sizes   : 32 bits physical, 32 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 39
model name      : Intel(R) Atom(TM) CPU Z2480  @ 2.00GHz
stepping        : 2
cpu MHz         : 600.000
cache size      : 512 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 1
apicid          : 1
initial apicid  : 1
fdiv_bug        : no
hlt_bug         : no
f00f_bug        : no
coma_bug        : no
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx constant_tsc arch_perfmon
 pebs bts nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 xtpr pdcm movbe lahf_lm arat dts tpr_shadow vnmi flexpriority
bogomips        : 3993.60
clflush size    : 64
cache_alignment : 64
address sizes   : 32 bits physical, 32 bits virtual
power management:

**Comment by avdimdv** [comment]
uname -m returns "i686" on my phone.

Also http://stackoverflow.com/questions/11989629/api-call-to-get-processor-architecture
System.getProperty("os.arch"); 

For additional safe you may try to extract binary in neutral place and execute it with -v to check result.

**Comment by koush** [comment]
Fixed, thanks.
I had only fixed this in the zip installer, forgot about this part.

Using System.getProperty now.

https://github.com/koush/Superuser/commit/2c1a38b66206b64b074e308587b36e315bb5fcc7
