### ISSUE TITLE
Updating su binary fails on HTC Nexus One with stock 2.3.6 rooted ROM (used to work before)

### ISSUE THREAD

**Issue by pdecat** [koush/Superuser#142]
Trying to updating the su binary fails on my rooted HTC Nexus One.
I'm using the stock 2.3.6 ROM and recovery so cannot use the alternative method.

It used to work before the last Superuser updates from Google Play.

Here's the logcat:

<pre>
E/su      ( 1464): sudb - Opening database
E/su      ( 1464): sudb - Database opened
E/su      ( 1464): sudb - Database closed
D/su      ( 1464): 10083 com.koushikdutta.superuser executing 0 /system/bin/sh using shell /system/bin/sh : sh
I/TelephonyRegistry(  102): notifyServiceState: 0 home F SFR (N/A) 20810  UMTS CSS not supported -1 -1RoamInd: -1DefRoamInd: -1EmergOnly: false
I/TelephonyRegistry(  102): notifyDataConnection: state=2 isDataConnectivityPossible=true reason=null interfaceName=rmnet0 networkType=3
I/Superuser( 1211): Result: 3.0.3
W/System.err( 1211): java.lang.Exception: unknown su
W/System.err( 1211):    at com.koushikdutta.superuser.util.SuHelper.checkSu(SuHelper.java:17)
W/System.err( 1211):    at com.koushikdutta.superuser.MainActivity$3.run(MainActivity.java:177)
</pre>

**Comment by koush** [comment]
That's not an error, that is ChainsDD's old su.

**Comment by pdecat** [comment]
Ok, so previous versions of Superuser must also failed to upgrade it, but not say so...
I'm surprised Superuser did work at all with the wrong su binary.

**Comment by pdecat** [comment]
Fixed it by copying the right su from my Galaxy Nexus to my Nexus One.

**Comment by pdecat** [comment]
Ok, the source of my issue is that I used bexboot to root my Nexus One: http://code.google.com/p/bexboot/
This custom boot image reinstalls Superuser on boot:

<pre>
$ adb shell ls -l /bexboot
-rw------- system   system        335 2011-11-07 20:17 bexboot.sh
-rw------- system   system     785801 2008-02-29 02:33 Superuser.apk
-rw------- system   system      22228 2008-02-29 02:33 su
$ adb shell cat /bexboot/bexboot.sh
mount -o rw,remount -t ext3 /dev/block/platform/s3c-sdhci.0/by-name/system /system
rm /system/bin/su
rm /system/xbin/su
mkdir /system/xbin
cat /bexboot/su>/system/xbin/su
chmod 4755 /system/xbin/su
cat /bexboot/Superuser.apk>/system/app/Superuser.apk
mount -o ro,remount -t ext3 /dev/block/platform/s3c-sdhci.0/by-name/system /system
</pre>
