### ISSUE TITLE
Request: ability to override cyanogenmod-specific behaviors without forking su code

### ISSUE THREAD

**Issue by djp952** [koush/Superuser#144]
I think it would be a nice feature if there was a predefined and supported way for the embedded Superuser build to override the CyanogenMod-specific behavior in su.c.  For example, I forked Superuser just to change access_disabled() so that my non-CM-based ROM could take advantage of the Superuser Access setting.  I also removed the bit about ro.debuggable needing to be set to one, ignored the build type, etc.  All very minor changes that are specific for that code to work with my particular builds, but ultimately I still had to fork the repo to accomplish it.

Perhaps something as simple as breaking out the CM-specific bit(s) into their own C file and allowing for an override to that file be specified with a build property? Developers could then decide how they can best implement those function(s) for their device/build without needing to completely ape the CyanogenMod code.  It may even lend itself as being useful for additional device/build specific edits if any become common in the future.

Thanks for the consideration, and more importantly thanks for making your excellent work here free and transparent for all to benefit from, it's greatly appreciated!

**Comment by koush** [comment]
You shouldn't need to change access_disabled. You can set the prop like any other rom, and in fact would also work on stock. It's just a persist.sys setting.

**Comment by djp952** [comment]
But only if you have an "ro.cm.version" property set .. all the code in access_disabled() is skipped without it, preventing the specific Apps/ADB Access conditions from being checked at all.

I was thinking more about ROMs that would still like to have the Access settings to be functional, but don't necessarily follow all of the same rules as CM.  I like to keep ro.debuggable set to "0" on all builds, for example.  Based on the current code, even if I set an "ro.cm.version" property to something fake to enable the checks, all su access would just be denied because ro.debuggable is not "1".  Stuff like that .... little differences that would break or limit some functionality.

No worries either way, this new Superuser is pretty fantastic as-is, and being 100% public it's just a couple clicks to fork and change the behavior slightly for different environments.  Just thought it might be something that would come in handy and potentially reduce the amount of out-of-baseline code out there.

**Comment by koush** [comment]
Oh, I did not realize there was an ro.cm.version check; that is unnecessary (and vestigal code from the port). I've removed it and will check it in shortly.

**Comment by koush** [comment]
Yeah, I'll need to mess with this to handle defaults in CM vs the rest of the world. I'll fix this to accomodate your suggestions. I didn't realize this was completely busted on non-cm.
