### ISSUE TITLE
Clocksync can get root when blacklisted

### ISSUE THREAD

**Issue by ogr3** [koush/Superuser#145]
I've been using clocksync for NTP sync.

Recently I noticed that it takes a lot of time for it to get root when you select synchronize. I tried to get around it by deleting it from the list in Superuser.

Now it still synchronizes time (which requires root) and the Superuser dialog does not show up.

https://play.google.com/store/apps/details?id=ru.org.amip.ClockSync

Badly behaving Superuser request in the app could possibly account for the slow request, but it should not be able to get superuser access after being removed from the list.

**Comment by ogr3** [comment]
Update: I got a reply from the developer, and the app is not supposed to ask for root if _Restore Permissions_ is not checked in the clocksync app (It uses Superuser to set the writeable bit on /dev/alarm) . However, Superuser still shows the Toast Superuser granted everytime I sync. But I guess that would be a bug in the app? Or that the system restores the write permissions automatically after a while?

**Comment by koush** [comment]
Log?

**Comment by ogr3** [comment]
Can't recreate. Reset the permissions on /dev/alarm to 664 and then the app works as intended, requesting root when it needs to change it to 666, and not when it has write access.

Guess my /dev/alarm was in a weird state or something.
