### ISSUE TITLE
Android 4.1 branch

### ISSUE THREAD

**Issue by tonyp** [koush/Superuser#147]
Would it be possible for you to add dedicated branches for building Superuser for Android 4.1?
I included SuperUser into CM10, but had to fix a couple issues:

koush/Superuser/Superuser/src/com/koushikdutta/superuser/Helper.java
- all references to android.os.UserManager

koush/Widgets/Widgets/res/layout-large/container_activity.xml:
- layout_marginEnd
- layout_marginStart

koush/Superuser/Superuser/res/layout-land/log_item.xml
- paddingEnd
- paddingStart

**Comment by koush** [comment]
Sorry, no. Supporting backwards compat on integrated builds is not a project goal. It would be outdated in a matter of months.

You're more than welcome to do that in your own fork.
