### ISSUE TITLE
Instructions on update from alternate version ?

### ISSUE THREAD

**Issue by d-faure** [koush/Superuser#153]
Even if this seems as trivial as a regular playstore installation, it would be nice to provide some hints on how to safely migrate from other utility to this one (chainsdd's / SuperSU / ...)

How valuable would be this post?  http://forum.xda-developers.com/showpost.php?p=39831040&postcount=2701

**Comment by ogr3** [comment]
If the other app plays nicely (i.e. just uses a SuperUser.apk and a su binary in the usual places) the easiest and cleanest way would be to flash the zip the first time. This works for ChainsDD's SuperUser and SuperSU.

SuperSU leaves some crap behind, and I don't think it's installer removes it either. (namely /system/bin/.ext/.su). Only way to get rid of that would be to remove the file yourself. This was up until version 1.10, after that I haven't looked at the SuperSU install script.

**Comment by koush** [comment]
I don't want to be responsible for providing instructions on how to clean up another Superuser or SuperSU app...

There's a built in install process in this app. It won't remove the other apps though, and that is not my intent.

**Comment by d-faure** [comment]
BTW, I found that the Superuser archive I intented to update, was in fact a mix of two packages (ChainsDD Superuser + some Busybox stuff). I managed to do the update (of the superuser part) by both flashing the zip from recovery and removing artifacts of previous installation left in the dalvik cache.
