### ISSUE TITLE
Mounting /system r/w sometimes causes reboot on Xperia Z

### ISSUE THREAD

**Issue by MicOestergaard** [koush/Superuser#157]
Mounting the system and/or writing/deleting files from /system will cause the Sony Xperia Z to reboot when the bootloader is locked.

The same issue is present for SuperSU, whereas the old Superuser app by ChainsDD does not have this problem.

**Comment by koush** [comment]
You can use the recovery install.
I won't special case installations for every single phone quirk.

I'm surprised the ChainsDD one doesn't exhibit this. It probably does, but it may just be an intermittent issue.
