### ISSUE TITLE
-c behavior only execs immediately subsequent arg

### ISSUE THREAD

**Issue by nuclearmistake** [koush/Superuser#158]
With SuperSU's su: [CODE]su -c make me a sandwich[/CODE] makes me a sandwich.
To make a sandwich with the included su: [CODE]su -c "make me a sandwich"[/CODE]

Would be nice if either worked.
I'll wrap my head around the arg handling and pull request this modification if I find time to.

You the man, Koush

**Comment by koush** [comment]
I am fairly sure the latter is correct. From man pages on my desktop, note the multiword example requires quotes:

```
EXAMPLES
     su man -c catman
            Runs the command catman as user man.  You will be asked for man's password unless your real UID
            is 0.
     su man -c 'catman /usr/share/man /usr/local/man'
            Same as above, but the target command consists of more than a single word and hence is quoted for
            use with the -c option being passed to the shell.  (Most shells expect the argument to -c to be a
            single word).
```
