### ISSUE TITLE
[Request] Eclair version of Superuser

### ISSUE THREAD

**Issue by ghost** [koush/Superuser#159]
Please add possibility to install Superuser on Android 2.1 Eclair devices (and older versions, if possible).

Maybe someone can think that "Eclair is too old", "Eclair is not supported even by Google - no Google Play updates" and "New phones have at least Gingerbread now". But even now, people are deciding to buy older, but cheaper devices to have possibility to use Android. Custom ROMs have serious bugs, so it's bad to use them as "daily driver". (Even me, Android enthusiast, I am using Eclair, because don't want 4hrs battery life, or low performance.)

Superuser app is **Froyo+ only**, so when people are using stock ROMs, they must install obsolete ChainsDD's Superuser, or SuperSU that torments user with toasts like "Granted SU rights for XXXXXX. Please consider buying Pro version". And both SUs are not open source, as you know.

So, please add possibility to download and/or build Eclair Superuser's version. I know there may be not possible to apply Holo theme, or some other goodies, but please try to give SU freedom for older phones!

**Comment by koush** [comment]
Sorry, eclair has less than 1.5% of the total android footprint. I'm not going to backport that far.

**Comment by koush** [comment]
http://developer.android.com/about/dashboards/index.html
