### ISSUE TITLE
Ask for lock mechanism like sudo in Unix

### ISSUE THREAD

**Issue by ilarrain** [koush/Superuser#162]
It would be a great security enhancement if the superuser app asked for the lock pattern/pin/password when granting superuser permissions. Just like sudo on Unix. At least as an option.

**Comment by koush** [comment]
It does. You configure it to ask for a pin or password.

**Comment by ilarrain** [comment]
Just noticed. Sorry.
Anyway, it would be great if it asked for the device's lock
pin/password/pattern instead of a custom one.

**Comment by koush** [comment]
There's no easy way to do that as far as I know.

Would need to go retrieve a hashed pw from some file in /data/system, or add hooks to the framework to support this.

The latter would break the stock/aftermarket installation scenario
