### ISSUE TITLE
SuperUser 1.0.2.1 binary update FC (can not report)

### ISSUE THREAD

**Issue by realJoshByrnes** [koush/Superuser#173]
Steps to reproduce:
- Receive 1.0.2.1 app update from the Play Store (am in beta group)
- Click on recovery install after binary notification
  APP CRASH. Went to report, but the device reboots (as expected) into CWM.

Note: Everything does actually work. (binary downloads and installs correctly)

Device: Nexus 4, using stock Android 4.3.

**Comment by koush** [comment]
This isn't actually an issue with superuser... rebooting the device forcibly like that can cause force closes of all sorts of apps. Not sure why.
