### ISSUE TITLE
Not possible to update binary without custom recovery on 4.3?

### ISSUE THREAD

**Issue by ogr3** [koush/Superuser#174]
Before 4.3 if you updated Superuser on play on a stock device you could update the binary by pressing OK in the dialog. Now it only shows cancel and recovery.

Is it not possible to update the binary without a custom recvovery if you're on stock 4.3?

This is on a takju Galaxy Nexus, everything stock except Superuser-4.3beta4 flashed in.

**Comment by koush** [comment]
Correct. Daemon can't be stopped once started. So installation over it wouldn't work.

There's ways to work around this (shutdown command, move/delete file). But I punted on those until I can get to it.

**Comment by sparkym3** [comment]
I am far from a linux expert, but I thought you could delete/overwrite files that were in use on a linux system since it would still remain, under the covers, unit all uses of it were removed.

Wouldn't this allow the app to update the binary to the most recent and then upon reboot start using the new binary?  It may not be as smooth as updating and automatically switching over to the new binary, but it would work in the interim.

**Comment by koush** [comment]
@sparkym3 Simply deleting the file fails if the daemon is running. Rename works though.

**Comment by sparkym3** [comment]
I can confirm this process for those who do not have custom recovery.  Copy new binary to xbin with a different name and set proper permissions.  Rename old su to something.  Rename new binary to su.  Reboot.

**Comment by alktlr** [comment]
Maybe this is a stupid question. But where is the new su binary located on the device? Getting the su binary out of date notification and is on stock ROM and recovery.

**Comment by koush** [comment]
@alktlr Are you "fixing root" after recovery exits?

**Comment by alktlr** [comment]
No, I want to keep it as stock as possible, making new ROM updates as painless as possible. Fastbooting CWM recovery when needing it.

**Comment by koush** [comment]
I mean are you choosing the "fix root" option after installing it via recovery

**Comment by alktlr** [comment]
I do not recall there was a "fix root" option or question when installing superuser-4.3-beta3.zip in recovery if that is what you mean. Btw its a Nexus 4.

**Comment by pjc123** [comment]
I lost root and TWRP when I updated to 4.3 as would be expected.  So I re-installed the latest TWRP and I downloaded the superuser.zip from Google Play (I assume that it is your latest 4.3 compatible version).  Once I install superuser.zip via TWRP, is the next step to select the "fix root" option to re-root and then I am done?  I did not do the "fix root" step when I unrooted 4.2.2, so I am a bit confused.

**Comment by koush** [comment]
I'm not speaking of TWRP, just CWM.

@alktlr Try installing the final superuser.zip. The beta3 had some issues.

**Comment by pjc123** [comment]
Oops.  I apologize for interjecting in the middle of your thread.  I will now try installing your program.

EDIT: By the way, superuser installed flawlessly and all my "root only" apps are working fine with it.  Thanks for all the hard work on this.

**Comment by alktlr** [comment]
Downloaded and installed the latest superuser.zip and the su binary out of date notification is gone. Thanks. Had not seen the link in Google Play if pjc123 had pointed me in that direction. Maybe you should add a not note in there if you have troubles then try install the superuser.zip again. Not sure if that helps the issue by OP.

**Comment by hellomoto124** [comment]
Hello , I can build myself ROM (android 4. 3)by myself , however, how to build  image for rooted device by change some source code to work well with superupser.apk,  could you give me some comments  ?﻿ 
by the way, adb root is available on my ROM , and adb remount is avaiable as well. however, some special apk still not get the root permission.

**Comment by x3rAx** [comment]
# Workaround:

See ~> https://github.com/koush/Superuser/issues/216#issuecomment-38354585

---

This seems to be related to the following: #216, #214, #185 , #233

**Comment by lusoelay** [comment]
#217
