### ISSUE TITLE
Install from recovery fails after 4.3 security update OTA

### ISSUE THREAD

**Issue by Fish-in-a-Barrel** [koush/Superuser#190]
I've been running 4.3 with Superuser for a while now without a problem.

After installing the 4.3 security update OTA for my HTC One GP (version jwr66y.h1), Superuser asked me to update the binaries.  I downloaded the latest zip (1.0.2.1) and installed from CWM recovery.  After rebooting, Superuser still insists that it is out of date, and none of my root apps work.

I may have made things worse at this point by trying to install SuperSU 1.65, which also failed.  I then went back into recovery and reinstalled Superuser.

I reviewed [issue 90](https://github.com/koush/Superuser/issues/90), which seems similar.  Here is some of the information you requested in that issue:

**ls -l /system/bin/su**

```
lrwxrwxrwx root     root              2013-09-25 22:12 su -> /system/xbin/su
```

**ls -l /system/xbin/su**

```
-rwsr-sr-x root     root       371104 2013-09-25 22:12 su
```

**ls -l /system/etc/install-recovery.sh**

```
-rw-r--r-- root     root          629 2013-09-25 22:00 install-recovery.sh
```

**ls -la /system/etc/.***

```
-rw-r--r-- root     root            2 2013-09-25 22:00 .has_su_daemon
-rw-r--r-- root     root            2 2013-09-25 22:00 .installed_su_daemon
```

**cat /system/etc/install-recovery.sh**

```
#!/system/bin/sh

# If you're implementing this in a custom kernel/firmware,
# I suggest you use a different script name, and add a service
# to launch it from init.rc

# Launches SuperSU in daemon mode only on Android 4.3+.
# Nothing will happen on 4.2.x or older, unless SELinux+Enforcing.
# If you want to force loading the daemon, use "--daemon" instead

/system/xbin/daemonsu --auto-daemon &

# Some apps like to run stuff from this script as well, that will
# obviously break root - in your code, just search this file
# for "install-recovery-2.sh", and if present, write there instead.

/system/etc/install-recovery-2.sh
```

**Comment by ldt116** [comment]
During the testing for https://github.com/koush/Superuser/issues/189 I've been switching between SuperSU and Superuser on the same ROM (HTC One converted to GE JWR66Y) and have had the same problem with the superuser recovery zip.

The trick is to delete .../xbin/su .../xbin/daemonsu ../etc/.installed_su_daemon and .../etc/.has_su_daemon in recovery adb before trying to install Superuser zip. That worked for me.

**Comment by Fish-in-a-Barrel** [comment]
That fixed it!

Thanks.

**Comment by koush** [comment]
Correct. I have let Chainfire know about his bug in SuperSu that is affecting Superuser.
