### ISSUE TITLE
"Superuser granted to shell" Toast shows several times when capturing a bug report

### ISSUE THREAD

**Issue by mhbrown** [koush/Superuser#215]
On a Nexus 5 running Kit Kat, when I press the 3 buttons (Vol Up + Vol Down + Power) simultaneously, first there is a vibration indicating that the bug report capture started. Then, after a few seconds, a toast reading "Superuser granted to Shell" pops up continuously for several minutes. I've seen this sometimes cause apps to crash as well. I tried it on another Nexus 5 with similar setup except SuperSU instead of Superuser and the issue was not present. I've seen this issue on two Nexus 5's with the same Superuser setup though.

**Comment by koush** [comment]
What version of Superuser? I just did a bug report last night without any issues.

**Comment by mhbrown** [comment]
App Version 1.0.2.8
Su Binary Version 15 com.koushikdutta.superuser

When this problem occurs, I also can't run any privileged commands until I reboot the phone. I just did a logcat capture running "su" in adb and this is what came up:
D/su      ( 9997): su invoked.
D/su      ( 9997): starting daemon client 2000 0
E/su      ( 9997): connect failed with 111: Connection refused

Rename to .zip and extract for bug report in case it helps:
![bugreport-2013-12-03-10-34-14 zip](https://f.cloud.github.com/assets/2215917/1666734/48c4c9f6-5c4b-11e3-82a3-96e93feece9f.jpg)

**Comment by Huexxx** [comment]
This issue is related to mine...

https://github.com/koush/Superuser/issues/207

The toast remains on screen several seconds...

It happens to me getting bug reports, and running certain apps.

Apps affected: Titanium Backup, Catlog
Apps don't affected: Helium, Root Explorer

The toast on screen is related to multiple su petitions that overlap the toast on screen. It has something to do with selinux because you can see certain logs on dmesg regarding denials... but it happens in both modes, enforcing and permissive.

**Comment by Huexxx** [comment]
I think that is sh related. Maybe in affected cases sh is used. I'm on nexus5 too.

**Comment by koush** [comment]
Stock + root?

**Comment by Huexxx** [comment]
No, is myself compiled Rom, based on KRT16S sources, with some additions
from cm and with your latest superuser embedded. Stock toolchain, stock
kernel. It's 99% stock. You can see my modified sources on my github:
https://github.com/huexxx

The repos are all beginning with zeus.

If you need some specific log/test, contact me.

Thanks and regards.

**Comment by mhbrown** [comment]
I'm on the stock ROM. Also just FYI, all of the above info I posted was using Dalvik runtime. I just switched to ART and tested again. The toast still pops up several times, but it doesn't seem to slow down the UI. Also, executing 'su' from adb shell I can see that it exits with exit code 0 (was exit code 1 with Dalvik). So, there is a difference there..

**Comment by Huexxx** [comment]
10 minutes after the bugreport, I still get toasts granting sh...

Bugreport:
http://dl.dropboxusercontent.com/u/4629711/N5/bugreport-2013-12-05-09-54-30.txt

Dmesg after 10 minutes:
http://dl.dropboxusercontent.com/u/4629711/N5/dmesg.txt

Regards.

2013/12/5 Koushik Dutta notifications@github.com

**Comment by koush** [comment]
Is this a new bug or has it been around a while?

**Comment by mhbrown** [comment]
I hadn't noticed it before (on previous phones, Android versions, Superuser or su versions). I haven't actively tested for it on older versions either though. Nexus 5 is my only phone now but I could try other versions of su or Superuser if it would help. Just let me know what to try.

**Comment by Huexxx** [comment]
My first build with your superuser embedded was up on 23/11/13, on nexus5
and almost pure aosp sources, and the problem was there.

To say that I haven't tried art yet.

Regards.

**Comment by kurnia76** [comment]
Was an error installing superuser from htc x720d help me.

**Comment by mhbrown** [comment]
This issue appears to have been resolved in the latest su binary update. Thanks!

**Comment by kurnia76** [comment]
[Superuser] "Superuser granted to shell" Toast shows several times when
capturing a bug report (#215)

**Comment by Sound-Proof** [comment]
I added you

**Comment by SHMAUS-Carter** [comment]
it's back. I see this message rather often still even in 1.0.3.0
