### ISSUE TITLE
Main Screen does not report approved apps when PIN protection is enabled

### ISSUE THREAD

**Issue by adajw** [koush/Superuser#23]
Superuser does not save details of any app approved while pin protection is enabled. Logging is not affected.

**Comment by nicksmith53** [comment]
See #6

**Comment by koush** [comment]
i believe this has been fixed, I just haven't put out an update yet. I will do that soon. Been working on CM integration.

**Comment by adajw** [comment]
Sorry for duplicate, the github android app doesn't show closed issues. Glad to hear it's fixed :)

**Comment by koush** [comment]
confirmed fixed

**Comment by ogr3** [comment]
I just got this bug with the latest code from git. 

Did rm -rf of /data/data/com.koushikdutta.superuser

Then a clean flash. List is empty after granting five apps successfully. 

Trying to use them again triggers the superuser dialog. If i remove the PIN, the apps gets added to the grant list again.

Problem with a clean install? @koush

**Comment by koush** [comment]
I'll test some more, thanks

**Comment by koush** [comment]
Ok, verified fixed again, heh.
