### ISSUE TITLE
SU times out, and then rejects request, on 1.0.3.0

### ISSUE THREAD

**Issue by ghost** [koush/Superuser#232]
Hi!

I first thought this was issue #204, but I think it's different, since #204 should be solved.

This is on a Kyocera Event, with android 4.0.4 and mostly stock firmware (no upgrades to newer Android available, and custom roms not possible, so I'm stuck with this version :) ).

I'm using superuser 1.0.3.0, installed via Play store (install method, Kyocera Event doesn't like recovery I think)

Calling su just gives a timeout, and no access.

logcat shows this:
'D/su      ( 2599): su invoked.
D/su      ( 2599): /dev/com.koushikdutta.superuser/.socket2599
E/su      ( 2599): select failed with 17: File exists
W/su      ( 2599): request rejected (10071->0 /system/bin/sh)'

Version of su:
'# su.koush -v
16 com.koushikdutta.superuser'

Note that multiuser mode is 'none', so I think no '--user' is passed to am.
'# su.koush -u
none'

Is there anything I can do to help with resolving this issue?

Thank you!

**Comment by ghost** [comment]
Hmm, I wonder if it has to do with this:
'# am'
link_image[1936]:  4329 could not load needed library 'libandroid_runtime.so' for 'app_process' (link_image[1936]:  4329 could not load needed library 'libbluedroid.so' for 'libandroid_runtime.so' (link_image[1936]:  4329 could not load needed library 'libkcjprop_jni.so' for 'libbluedroid.so' (load_library[1091]: Library 'libkcjprop_jni.so' not found)))CANNOT LINK EXECUTABLE

Not sure though, that file 'libkcjprop_jni.so' seems to be here:
'# ls /sysprop/kcjprop/'
drwxrwx--x    3 root     root        4.0K Feb 14 19:53 .
drwxr-xr-x    4 root     root        4.0K Jan  1  1970 ..
-rw-r----x    1 root     root         302 Feb 14 19:53 clientid.prop
-rwxrwx---    1 root     root       29.0K Jan 11  2013 kcjprop_daemon
-rw-rw-r--    1 root     root        9.4K Jan 11  2013 libkcjprop_jni.so
drwxrwx--x    2 root     root        8.0K Feb 14 19:53 rw

No idea what it all means :)

**Comment by koush** [comment]
hm, seems LD_LIBRARY_PATH may have been smoked.

**Comment by ghost** [comment]
Right, this fixes it:
'# mount -o rw,remount /system'
'# cd /system/lib'
'# ln -s /sysprop/kcjprop/libkcjprop_jni.so'
'# ls -lah libkc*'
lrwxrwxrwx    1 root     root          34 Feb 14 21:31 libkcjprop_jni.so -> /sysprop/kcjprop/libkcjprop_jni.so
'# mount -o ro,remount /system'

But I have no idea why this is needed :)
Funnily enough, I think this is also why you can't update the 'ChainsDD superuser' su either on a Kyocera Event.
The Kyocera Event (and Rise) with 4.0.4 update needs a special method of rooting: http://forum.xda-developers.com/showthread.php?t=2307306
Mayby Kyocera 'accidentially' broke the rooting tools in their 4.0.4 update? :)

**Comment by koush** [comment]
Hm, that's really weird and nonstandard. So, I am actually not sure how to fix this. LD_LIBRARY_PATH sanitization is necessary to prevent a security hole on su invocation. Allowing wacky LD_LIBRARY paths like that wis a potentially dangerous issue.

**Comment by koush** [comment]
Ie, if I preserved LD_LIBRARY_PATH into the su invocation, that could be used to load and execute a rogue binary upon execution of su and all related sub processes.

**Comment by ghost** [comment]
Hmm, funny, or weird..
In terminals which have not called su, I have a (correct) LD_LIBRARY_PATH set.
In a terminal, after calling su, there is no LD_LIBRARY_PATH set.
So I guess in some cases (also when your 'su' is called) no LD_LIBRARY_PATH is set, and then the 'am/app_process' call fails.
I guess I need to figure out how/when LD_LIBRARY_PATH is set :)
And why sometimes it is not ;)
PS: Didn't see what you wrote above yet, when I wrote this :)
I guess you mean it's normal for LD_LIBRARY_PATH to be unset, and on 'normal' phones that's not an issue, but on the kyocera it's a issue because of the .so in a weird place, which is required for am?

**Comment by ghost** [comment]
Heh, yep, with a symlink to libkcjprop_jni.so in /system/lib the latest ChainsDD superuser su (3.1.1) also works on Kyocera Event (and Rise?). So I guess that's a workaround :)

**Comment by kurnia76** [comment]
su error install help me
