### ISSUE TITLE
PIN protection can be circumvented

### ISSUE THREAD

**Issue by Miwer** [koush/Superuser#239]
I have found a way to circumvent the PIN protection feature, but I will not disclose the details here. I have sent a bug report by e-mail to superuser at clockworkmod.com

Best regards,
Miwer

**Comment by koush** [comment]
please mail koush _at_ koushikdutta.com

**Comment by Miwer** [comment]
done :)

**Comment by koush** [comment]
thanks got it

**Comment by koush** [comment]
Responded via email:

Hi Michael,

I'm aware of this UX issue.

Superuser is built to prevent other _apps_ from surreptitiously getting root access, not users. This includes unauthorized users... if you want to protect your phone, employ a device pin (not a superuser pin).

The superuser pin is specifically to prevent fat fingering and accidentally pressing the "allow" button.

If your device is unlocked and you hand it to someone, all bets are pretty much off.

**Comment by koush** [comment]
Lemme know if you have any further comments.
