### ISSUE TITLE
Android L support

### ISSUE THREAD

**Issue by ogr3** [koush/Superuser#242]
Apparently Android L has moved the install-recovery.sh from /system/etc to /system/bin

So the Superuser zip will need a way to distinguish between pre-L and Android L and act accordingly.

**Comment by Fmstrat** [comment]
Following the directions to add this to an Android L AOSP repository do not work either. I see no Superuser files contained within the created otapackage. Also, the directions lack the requirement to remove "su" from frameworks/base.

**Comment by unforgettableid** [comment]
You should use [phhusson/Superuser](https://github.com/phhusson/Superuser) instead.  No binaries are available yet; see [here](https://github.com/phhusson/Superuser/issues/1).
