### ISSUE TITLE
Complete novice, out of his depth

### ISSUE THREAD

**Issue by stevolin77** [koush/Superuser#256]
Purchased a Q102 tablet which came already rooted and with Superuser installed. In my attempts to unroot the tablet so I can use the Sky Go app I have somehow got rid of the su binary?
I don't have a clue what I'm doing, or how I have managed to do what I have done.
If a good Samaritan would like to help me completely indoor my tablet, I would be very grateful

**Comment by stevolin77** [comment]
I of course meant 'unroot' not indoor

**Comment by stevolin77** [comment]
Why have you closed this? Not very helpful

**Comment by koush** [comment]
Github is not a place to open support tickets on an open source project. This is for development or bug reporting. Go to XDA for help.
