### ISSUE TITLE
PIN-protection dialog doesn't pop up

### ISSUE THREAD

**Issue by ogr3** [koush/Superuser#26]
I just built from Git and installed on Galaxy Nexus Stock 4.2.2.

All settings seem to work except PIN-protection. Nothing happens when I click the option. Logcat doesn't show anything.

Am I missing something?

**Comment by koush** [comment]
oh wait, i commented that out LOL
let me fix that.

**Comment by ogr3** [comment]
Good stuff!

I just tried it end the dialog shows :)
