### ISSUE TITLE
Feature request: Make Holo Dark selectable in the main menu.

### ISSUE THREAD

**Issue by ogr3** [koush/Superuser#32]
Right now the app is set to Holo Light and before it was using Holo Dark, which looks much better IMHO. 

Could you please make a toggle in the GUI between the two?

**Comment by koush** [comment]
wat

**Comment by ogr3** [comment]
You just changed these lines in styles.xml (https://github.com/koush/Superuser/commit/3981de050ef31dd064e67514727470b2e1bb1de8 ):

<code> <style name="RequestTheme" parent="RequestThemeLight" />
    <style name="Superuser" parent="SuperuserLight" />
</code>
They were set to Dark before (which looked much better). So I was hoping for a user-changeable toggle between the two Themes. Is that possible?

**Comment by koush** [comment]
https://github.com/koush/Superuser/commit/7c6f4e94656ca204103651643d2f375bbc6bc9e2

**Comment by ogr3** [comment]
Much appreciated. Looks great!
