### ISSUE TITLE
Log button still being shown in the log screen

### ISSUE THREAD

**Issue by ed10vi** [koush/Superuser#44]
The log button continues in the action bar when you are seeing the logs
![Screenshot_2013-03-03-14-51-05](https://f.cloud.github.com/assets/569353/214291/d7ce12a8-8409-11e2-95b0-d992033e1395.png)

**Comment by ogr3** [comment]
There is no button for getting back to the main screen from the log screen. Related?

**Comment by koush** [comment]
Press back.
