### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by dpashkevich** [koush/Superuser#5]
Thanks for creating another amazing app! :)
What license does this code have?

**Comment by williamtheaker** [comment]
FSF approved licenses: https://gnu.org/licenses/license-list.html#SoftwareLicenses
OSI approved licenses: http://opensource.org/licenses/alphabetical

**Comment by koush** [comment]
i'm debating between gpl and apache. leaning apache right now. will decide shortly.

**Comment by dpashkevich** [comment]
I wish I could be more helpful but I'm don't know that much about 
specific flavors of licenses...

On 25.02.2013 21:24, Koushik Dutta wrote:

> i'm debating between gpl and apache. leaning apache right now. will 
> decide shortly.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/koush/Superuser/issues/5#issuecomment-14062167.

## 

Dmitry Pashkevich

**Comment by maximumultraist** [comment]
I for one vouch for the GPL, but really, any GPL-compatible license would be fine. Copyleft licenses like the GPL prevent software licensed under said licenses to be linked to proprietary code, thereby eliminating people from modifying the software and adding proprietary features, then repackaging it. If you want this to be a "standard" SU app, copyleft would make the most sense.

**Comment by koush** [comment]
apache
