### ISSUE TITLE
Double log icons in action bar

### ISSUE THREAD

**Issue by ogr3** [koush/Superuser#57]
In 1.0.0.6.

Start superuser. Press home. Start again. Select a granted app. Now I have two icons for log and no trash icon in the action bar.

**Comment by koush** [comment]
k will investigate

**Comment by koush** [comment]
not seeing this bug on my phones, nexus 10 or nexus 4.

**Comment by ogr3** [comment]
My device is a maguro, stock yakju build. It shows sometimes by just opening the app again after having it open.

Try opening the GUI. Press home.

Grant a new app superuser.

Start superuser (in my case the list wasn't refreshed)

press back

start superuser again (app appears)

Could it be that some cases doesn't refresh the GUI?

**Comment by koush** [comment]
are you building from source or official play build?

**Comment by ogr3** [comment]
Official play build this time. Could it be residue due to the fact that I have had self built versions on this device?

Anything I should try removing?

**Comment by koush** [comment]
Not sure. Your build may not be clean? Try a clean build or something. And removing all instances of the apk.

**Comment by ogr3** [comment]
Ok,

rm -rf /data/data/com.koushikdutta.superuser

remove the apk.

flash superuser-1006.zip in recovery.

Can recreate the GUI not refreshing.

start superuser
press home
start connectbot
su
add connectbot to superuser whitelist
start superuser again
connectbot not added to the whitelist in the gui.
press back
start superuser
connectbot is showing in the list.

So the GUI not refreshing is one thing that's there in the 1006 version.

**Comment by ogr3** [comment]
Just got the original bug again.

Did nothing special, just had the screen of for half an hour and when I started Superuser again the double icons were there.

The menu was whack as well, showing duplicate rows for settings, but nothing happened when you clicked any option.

Pressing back all the way and then restarting the app solves it.

**Comment by koush** [comment]
Strange, I'll see if I can track this down. I wonder if I'm not managing the fragment lifecycle properly.

**Comment by koush** [comment]
Should be fixed with this:

https://github.com/koush/Widgets/commit/67155b00420ba1f4481ea7be3cc6f2b4dff976d0

Feel free to reopen if it is not.

Will need to pull both superuser and widgets.

**Comment by ogr3** [comment]
Was this fix in 1009 on play? 

In that case I got the error again.

**Comment by koush** [comment]
The fix has not been released yet, will need to build yourself to test
