### ISSUE TITLE
"Remember" doesn't work when pin protected

### ISSUE THREAD

**Issue by Fifteen15Studios** [koush/Superuser#6]
When an app doesn't have the permission to use SU, it pops up the window asking if you want to allow, and it gives the options "just once, for 10 minutes, or forever". This works fine until you use pin protection.

As soon as I enabled pin protection, it would pop-up this dialog every time an app requested SU access, even if I've already added it to the "forever" list. (This was especially annoying when using an app to backup my apps and their data.)

Issue occurred on a Nexus 10, running 4.2.2 stock.

**Comment by koush** [comment]
Cool, I can fix this, thanks for the report.

**Comment by koush** [comment]
Fixed in source, next beta will have the fix.
