### ISSUE TITLE
I think the chinese translation may have the extra backslash as well. 

### ISSUE THREAD

**Issue by ogr3** [koush/Superuser#60]
But I'll leave it to someone who actually understand the text:

.//Superuser/res/values-zh/strings.xml:    <string name="install_superuser_info">超級使用者的二進制檔案（su）一定要更新\n\n請選擇安裝方法\n\HTC 設備建議選擇回復模式（Recovery）的安裝方法</string>
.//Superuser/res/values-zh-rHK/strings.xml:    <string name="install_superuser_info">超級使用者的二進制檔案（su）一定要更新\n\n請選擇安裝方法\n\HTC 設備建議選擇回復模式（Recovery）的安裝方法</string>
.//Superuser/res/values-zh-rTW/strings.xml:    <string name="install_superuser_info">超級使用者的二進制檔案（su）一定要更新\n\n請選擇安裝方法\n\HTC 設備建議選擇回復模式（Recovery）的安裝方法</string>

**Comment by koush** [comment]
Yes it does

**Comment by koush** [comment]
fixed
