### ISSUE TITLE
Recovery update fails 1.0.0.6 -> 1.0.0.7

### ISSUE THREAD

**Issue by ogr3** [koush/Superuser#65]
maguro stock yakju.

Reboots into recovery, and ends up with the sad lying android with red exclamation mark.

power+vol up 

shows checking signature, installation aborted.

1.0.0.6 was installed using recovery zip.

**Comment by koush** [comment]
need a custom recovery installed.

**Comment by ogr3** [comment]
Crap, then I must tell everyone to NOT use the Recoveryfeature - people in general tend to not know what to do when the exclamation mark appears...

I thought you said yesterday that any recovery would work.

**Comment by koush** [comment]
I meant any custom recovery will work. Like ClockworkMod Recovery or TWRP or AmonRA, etc.

The device needs to be rooted already, which generally implies that a custom recovery was installed (as that is part of the installation process).

**Comment by koush** [comment]
To clarify, this app will NOT root Android for you.

**Comment by ogr3** [comment]
A lot of people running Nexus devices just boot custom recovery via fastboot when needed in order to receive OTA. 

So there could be a warning stating that a recovery install is pointless unless you have a custom recovery, which by no means is implied if the device is rooted.

Can you detect which recovery is installed?

In that case you could just not promote the recoveryinstall method if the recovery will not be able to handle it.
