### ISSUE TITLE
White screen on first confirmation after installing.

### ISSUE THREAD

**Issue by ghost** [koush/Superuser#68]
Just flashed superuser.zip. After booting I started Superuser once to check that the process worked (coming from SuperSU).

Then I started Titanuim Backup and got a white screen (Superuser Actionbar visible, there was a short glimpse of the actual confirmation screen but it immediatly turned white).

After pressing Back and restarting Titanium all went as expected, got the Superuser confirmation screen showing up.

**Comment by koush** [comment]
Can you let me know your supeuser apk version? It'll be in the About section.

**Comment by ghost** [comment]
Superuser 1.0.0.6
Device: Nexus 4, JDQ39

**Comment by koush** [comment]
I just tested, and it worked fine for me. Hrm.

**Comment by koush** [comment]
let me know if you can reproduce this problem.

**Comment by ghost** [comment]
Ok, will try to reproduce.

**Comment by ghost** [comment]
I have not been able to reproduce this, even with clearing Superuser data and reflashing the app.
