### ISSUE TITLE
Applist not updated.

### ISSUE THREAD

**Issue by ghost** [koush/Superuser#69]
Start Superuser, Applist contains some apps that have been granted su permission.
Press Home Button.
Launch another app thats not yet on the granted list, confirm Superuser request (permanently).
Press Home Button.
Start Superuser via Recent Apps List - the new App is not there yet.
Swipe away Superuser from the recent Apps List, start Superuser.
Now the List contains the new App.

Reproduced this several times by clearing all granted Apps.

Superuser 1.0.0.7
Nexus 4, JDQ39

**Comment by koush** [comment]
yeah, there's a refresh issue here. need to fix that. if you back out and reopen, it refreshes.

**Comment by koush** [comment]
fixed https://github.com/koush/Superuser/commit/d0a7a938a30bc853181581dac3e9985aa471b33a
