### ISSUE TITLE
uninitialized variable?

### ISSUE THREAD

**Issue by dvolgyes** [koush/Superuser#88]
I just ran "cppcheck" on the code, and it found a potential problem:
[Superuser/jni/su/su.c:177]: (error) Uninitialized variable: mode

The relevant code is below. What I do not understand is:
the "last" variable.
It looks for me that way:
- because "mode" is uninitialized, "last" can have any value

Maybe "mode" should be initalized and / or be static.
(Otherwise I cannot image how could it have meaningful data at the line where "strlen" is used on it.)

It also would be nice somehow protect against buffer overrun.
Imagine that: "mode" is uninitialized, there is no '\0\ in the first 12 bytes, so the ' mode[last]=' will write out from the area.
So last<=11 would be a nice check also. 
(It could change to a fallback solution, if last>11.)

The relevant parts on the su.c file:

```
int ret = MULTIUSER_MODE_OWNER_ONLY;
char mode[12];
FILE *fp;
if ((fp = fopen(REQUESTOR_MULTIUSER_MODE, "r"))) {
    int last = strlen(mode) - 1;
    if (mode[last] == '\n')
        mode[last] = '\0';
    fgets(mode, sizeof(mode), fp);
    if (strcmp(mode, MULTIUSER_VALUE_USER) == 0) {
        ret = MULTIUSER_MODE_USER;
    } else if (strcmp(mode, MULTIUSER_VALUE_OWNER_MANAGED) == 0) {
        ret = MULTIUSER_MODE_OWNER_MANAGED;
    }
    else {
        ret = MULTIUSER_MODE_OWNER_ONLY;
    }
    fclose(fp);
}
return ret;
```

**Comment by koush** [comment]
Will fix.

**Comment by koush** [comment]
https://github.com/koush/Superuser/commit/f54b506b93e0c26c94a04b908dcde442000b5913
