### ISSUE TITLE
AOSP 4.2.2 for Mako fails to work

### ISSUE THREAD

**Issue by inhies** [koush/Superuser#91]
I compiled Superuser in to the settings app on AOSP 4.2.2 for Mako (Nexus 4) and it's not working. I can `su` in ADB and get root, but nothing else can. The settings integration seemed to go fine, I don't get any force closes or anything. I cherry-picked patch set 5 from CM. 

Things I've done:
- Removed the default su app from the source tree as it causes a name conflict
- Added su as package to be included with the build
- Verified that the su binary works and is the one from this source and not some other project. I hex dumped it and found strings referenceing "koush" and "com.android.settings".

Not sure where to go with this, so I uploaded a logcat dump [here](http://n4.inhies.com/superuser.txt). Towards the end I opened Titanium Backup and let it try to get root, so there's something to look for. I can't really make sense of it, it's so noisy. 

If you need any more info just let me know, I love this app. Thanks.

**Comment by dalb8** [comment]
Perhaps my experience is related with 1.0.0.7. I've built the apk while changing the package id with aapt in the build.XML (it's for publishing on F-Droid.org). The app installs su but says it didn't work and apps can't get root. An update.zip flashed does work after the app in /data is uninstalled. And the app downloaded from Play Store works as expected.

**Comment by koush** [comment]
I'll make a cleaner patch, I assume you're looking at hte CM one.

The CM one has some CM specific namespacing.

**Comment by koush** [comment]
The integrated Superuser does not allow root install. Do you have a separate launcher icon for Superuser? You shouldn't.

**Comment by inhies** [comment]
dalb8: Your problem is definitely different than mine, you should open a separate issue for it if you can't figure it out.

koush: Yea I used the CM patch. It merged in to AOSP without issue but I'm not surprised to see there was issues when doing do :) Looking forward to an AOSP patch or something along those lines.

**Comment by koush** [comment]
Yeah, remove the CM specific naming (regarding fragments and other such class names in the xml files).

What you really want is patchset 2. Patchset 3 4 and 5 have CM specific stuff that requires changes in vendor/cm.

**Comment by inhies** [comment]
Ah ok. I'm not too handy with java, so I grabbed patchset 2 via cherry pick and am rebuilding now. Hopefully that's all I need to do otherwise I'm lost.

 I saw that you changed the link in the readme file to patchset 2 as well. Was there functional changes in the later patch sets, or just CM specific ones?

**Comment by koush** [comment]
Just CM specific patches in the later ones. The CM team wants the fragments and xml references to be in their namespace. A bit arbitrary and weird, so I just wrapped them with classes in the CM namespace.

**Comment by inhies** [comment]
Confirmed: Pulling patch set 2 fixes this. Thanks koush!
