### ISSUE TITLE
SU request dialog not working when su needs to be updated

### ISSUE THREAD

**Issue by holde** [koush/Superuser#97]
I updated SuperUser some hours ago. Jost now an app requested su and the dialogue popped on. Clicking Deny or Allow showed the Toast. SuperUser tried to return to the requesting app, but immediately popped back, asking again if I want to grant su access. I couldn't return to the app.

I had to manually open the Superuser app and then got a prompt that the binary is outdated.

I'm wondering if it's feasible to put this check in the su request dialogue.

Edit: I just noticed, that there was a notification that told me to update su, but I'm not sure when it came up since i didn't notice it.

**Comment by holde** [comment]
relevant(?) logcat:
03-06 17:12:19.808: DEBUG/DfeApi(26878): [1] DfeRequest.deliverResponse: Not delivering second response for request=[[ ] https://android.clients.google.com/fdfe/rev?doc=com.koushikdutta.superuser&sort=2 NORMAL 87]
03-06 17:12:19.898: DEBUG/DfeApi(26878): [1] DfeRequest.deliverResponse: Not delivering second response for request=[[ ] https://android.clients.google.com/fdfe/rec?c=3&rt=4&doc=com.koushikdutta.superuser NORMAL 86]
03-06 17:39:28.966: INFO/ActivityManager(591): Start proc com.koushikdutta.superuser for broadcast com.koushikdutta.superuser/.SuReceiver: pid=31843 uid=10125 gids={50125, 1028}
03-06 17:39:29.777: DEBUG/su(31876): /dev/com.koushikdutta.superuser/.socket31874
03-06 17:39:30.107: INFO/ActivityManager(591): START u0 {flg=0x10000000 cmp=com.koushikdutta.superuser/.RequestActivity (has extras)} from pid 31877
03-06 17:39:30.127: INFO/ActivityManager(591): Start proc com.koushikdutta.superuser:superuser for activity com.koushikdutta.superuser/.RequestActivity: pid=31893 uid=10125 gids={50125, 1028}
03-06 17:39:30.227: INFO/ActivityManager(591): START u0 {flg=0x10800000 cmp=com.koushikdutta.superuser/.MultitaskSuRequestActivity (has extras)} from pid 31893
03-06 17:39:30.678: INFO/ActivityManager(591): Displayed com.koushikdutta.superuser/.MultitaskSuRequestActivity: +442ms (total +553ms)
03-06 17:39:34.162: DEBUG/su(31930): /dev/com.koushikdutta.superuser/.socket31922
03-06 17:39:34.442: INFO/ActivityManager(591): START u0 {flg=0x10000000 cmp=com.koushikdutta.superuser/.RequestActivity (has extras)} from pid 31931
03-06 17:39:34.472: INFO/ActivityManager(591): START u0 {flg=0x10800000 cmp=com.koushikdutta.superuser/.MultitaskSuRequestActivity (has extras)} from pid 31893
03-06 17:39:34.752: INFO/ActivityManager(591): Displayed com.koushikdutta.superuser/.MultitaskSuRequestActivity: +256ms (total +290ms)
03-06 17:39:39.097: DEBUG/su(32005): /dev/com.koushikdutta.superuser/.socket32003
03-06 17:39:39.387: INFO/ActivityManager(591): START u0 {flg=0x10000000 cmp=com.koushikdutta.superuser/.RequestActivity (has extras)} from pid 32006
03-06 17:39:39.968: INFO/ActivityManager(591): START u0 {flg=0x10800000 cmp=com.koushikdutta.superuser/.MultitaskSuRequestActivity (has extras)} from pid 31893
03-06 17:39:40.248: INFO/ActivityManager(591): Displayed com.koushikdutta.superuser/.MultitaskSuRequestActivity: +272ms (total +347ms)
03-06 17:39:41.106: DEBUG/su(32140): /dev/com.koushikdutta.superuser/.socket32138
03-06 17:39:41.356: INFO/ActivityManager(591): START u0 {flg=0x10000000 cmp=com.koushikdutta.superuser/.RequestActivity (has extras)} from pid 32141
03-06 17:39:41.897: INFO/ActivityManager(591): START u0 {flg=0x10800000 cmp=com.koushikdutta.superuser/.MultitaskSuRequestActivity (has extras)} from pid 31893
03-06 17:39:42.107: INFO/ActivityManager(591): Displayed com.koushikdutta.superuser/.MultitaskSuRequestActivity: +210ms (total +242ms)
03-06 17:39:46.332: WARN/ActivityManager(591): Duplicate finish request for ActivityRecord{421b96e0 u0 com.koushikdutta.superuser/.MultitaskSuRequestActivity}
03-06 17:39:47.122: WARN/ActivityManager(591): Duplicate finish request for ActivityRecord{421b96e0 u0 com.koushikdutta.superuser/.MultitaskSuRequestActivity}
03-06 17:39:47.443: WARN/ActivityManager(591): Duplicate finish request for ActivityRecord{421b96e0 u0 com.koushikdutta.superuser/.MultitaskSuRequestActivity}
03-06 17:39:47.683: WARN/ActivityManager(591): Duplicate finish request for ActivityRecord{421b96e0 u0 com.koushikdutta.superuser/.MultitaskSuRequestActivity}
03-06 17:39:49.335: WARN/ActivityManager(591): Duplicate finish request for ActivityRecord{421b96e0 u0 com.koushikdutta.superuser/.MultitaskSuRequestActivity}
03-06 17:39:49.545: DEBUG/su(32196): /dev/com.koushikdutta.superuser/.socket32194
03-06 17:39:49.875: INFO/ActivityManager(591): START u0 {flg=0x10000000 cmp=com.koushikdutta.superuser/.RequestActivity (has extras)} from pid 32197
03-06 17:39:49.925: INFO/ActivityManager(591): START u0 {flg=0x10800000 cmp=com.koushikdutta.superuser/.MultitaskSuRequestActivity (has extras)} from pid 31893
03-06 17:39:50.156: INFO/ActivityManager(591): Displayed com.koushikdutta.superuser/.MultitaskSuRequestActivity: +224ms (total +257ms)
03-06 17:39:57.113: DEBUG/su(32277): /dev/com.koushikdutta.superuser/.socket32275
03-06 17:39:57.363: INFO/ActivityManager(591): START u0 {flg=0x10000000 cmp=com.koushikdutta.superuser/.RequestActivity (has extras)} from pid 32278
03-06 17:39:57.924: INFO/ActivityManager(591): START u0 {flg=0x10800000 cmp=com.koushikdutta.superuser/.MultitaskSuRequestActivity (has extras)} from pid 31893
03-06 17:39:58.114: INFO/ActivityManager(591): Displayed com.koushikdutta.superuser/.MultitaskSuRequestActivity: +178ms (total +225ms)
03-06 17:40:02.989: DEBUG/su(32310): /dev/com.koushikdutta.superuser/.socket32307
03-06 17:40:03.250: INFO/ActivityManager(591): START u0 {flg=0x10000000 cmp=com.koushikdutta.superuser/.RequestActivity (has extras)} from pid 32311
03-06 17:40:03.800: INFO/ActivityManager(591): START u0 {flg=0x10800000 cmp=com.koushikdutta.superuser/.MultitaskSuRequestActivity (has extras)} from pid 31893
03-06 17:40:04.030: INFO/ActivityManager(591): Displayed com.koushikdutta.superuser/.MultitaskSuRequestActivity: +224ms (total +261ms)
03-06 17:40:08.125: DEBUG/su(32366): /dev/com.koushikdutta.superuser/.socket32364
03-06 17:40:08.385: INFO/ActivityManager(591): START u0 {flg=0x10000000 cmp=com.koushikdutta.superuser/.RequestActivity (has extras)} from pid 32367
03-06 17:40:08.936: INFO/ActivityManager(591): START u0 {flg=0x10800000 cmp=com.koushikdutta.superuser/.MultitaskSuRequestActivity (has extras)} from pid 31893
03-06 17:40:09.146: INFO/ActivityManager(591): Displayed com.koushikdutta.superuser/.MultitaskSuRequestActivity: +184ms (total +225ms)
03-06 17:40:13.150: DEBUG/su(32413): /dev/com.koushikdutta.superuser/.socket32411
03-06 17:40:13.410: INFO/ActivityManager(591): START u0 {flg=0x10000000 cmp=com.koushikdutta.superuser/.RequestActivity (has extras)} from pid 32414
03-06 17:40:13.991: INFO/ActivityManager(591): START u0 {flg=0x10800000 cmp=com.koushikdutta.superuser/.MultitaskSuRequestActivity (has extras)} from pid 31893
03-06 17:40:14.221: INFO/ActivityManager(591): Displayed com.koushikdutta.superuser/.MultitaskSuRequestActivity: +227ms (total +277ms)
03-06 17:40:17.755: DEBUG/su(32511): /dev/com.koushikdutta.superuser/.socket32509
03-06 17:40:18.075: INFO/ActivityManager(591): START u0 {flg=0x10000000 cmp=com.koushikdutta.superuser/.RequestActivity (has extras)} from pid 32512
03-06 17:40:18.636: INFO/ActivityManager(591): START u0 {flg=0x10800000 cmp=com.koushikdutta.superuser/.MultitaskSuRequestActivity (has extras)} from pid 31893
03-06 17:40:18.886: INFO/ActivityManager(591): Displayed com.koushikdutta.superuser/.MultitaskSuRequestActivity: +247ms (total +281ms)
03-06 17:40:27.986: INFO/ActivityManager(591): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.koushikdutta.superuser/.MainActivity bnds=[596,788][744,952]} from pid 8329
03-06 17:40:28.156: INFO/Superuser(31843): Result: 2 com.koushikdutta.superuser
03-06 17:40:28.166: WARN/System.err(31843): at com.koushikdutta.superuser.util.SuHelper.checkSu(SuHelper.java:21)
03-06 17:40:28.166: WARN/System.err(31843): at com.koushikdutta.superuser.MainActivity$7.run(MainActivity.java:274)
03-06 17:40:28.717: INFO/ActivityManager(591): Displayed com.koushikdutta.superuser/.MainActivity: +699ms
03-06 17:40:32.841: DEBUG/su(32612): 10125 com.koushikdutta.superuser executing 0 /system/bin/sh using shell /system/bin/sh : sh
03-06 17:40:33.111: INFO/Superuser(31843): Result: 6 com.koushikdutta.superuser
03-06 17:51:56.220: INFO/ActivityManager(591): START u0 {cmp=com.koushikdutta.superuser/.MainActivity bnds=[0,242][768,370]} from pid -1
03-06 17:51:56.220: WARN/ActivityManager(591): startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.koushikdutta.superuser/.MainActivity bnds=[0,242][768,370] }
03-06 17:51:56.331: INFO/Superuser(31843): Result: 6 com.koushikdutta.superuser
03-06 17:51:56.471: INFO/ActivityManager(591): Displayed com.koushikdutta.superuser/.MainActivity: +226ms
03-06 18:10:20.659: INFO/ActivityManager(591): No longer want com.koushikdutta.superuser:superuser (pid 31893): empty for 1802s

and

03-06 17:12:18.006: DEBUG/su(29468): su invoked.
03-06 17:12:18.226: DEBUG/su(29482): su invoked.
03-06 17:13:23.215: DEBUG/SurfaceFlinger(162): Screen released, type=0 flinger=0x4001f3a8
03-06 17:13:23.385: DEBUG/Surface(591): Excessive delay in blankDisplay() while turning screen off: 174ms
03-06 17:13:29.412: DEBUG/SurfaceFlinger(162): Screen acquired, type=0 flinger=0x4001f3a8
03-06 17:36:17.131: INFO/SubscribedFeeds(7338): Received message
03-06 17:39:28.626: DEBUG/su(31792): su invoked.
03-06 17:39:28.626: DEBUG/su(31794): db allowed
03-06 17:39:28.626: DEBUG/su(31796): 10123 oliver.ehrenmueller.dbadmin executing 0 /system/bin/sh using shell /system/bin/sh : sh
03-06 17:39:29.777: DEBUG/su(31875): su invoked.
03-06 17:39:29.777: DEBUG/su(31876): /dev/com.koushikdutta.superuser/.socket31874
03-06 17:39:30.307: DEBUG/su(31906): waiting for user
03-06 17:39:34.051: DEBUG/su(31916): 10123 oliver.ehrenmueller.dbadmin executing 0 /system/bin/sh using shell /system/bin/sh : sh
03-06 17:39:34.152: DEBUG/su(31929): su invoked.
03-06 17:39:34.162: DEBUG/su(31930): /dev/com.koushikdutta.superuser/.socket31922
03-06 17:39:34.642: DEBUG/su(31959): waiting for user
03-06 17:39:38.977: DEBUG/su(31995): 10123 oliver.ehrenmueller.dbadmin executing 0 /system/bin/sh using shell /system/bin/sh : sh
03-06 17:39:39.097: DEBUG/su(32005): /dev/com.koushikdutta.superuser/.socket32003
03-06 17:39:39.097: DEBUG/su(32004): su invoked.
03-06 17:39:40.098: DEBUG/su(32038): waiting for user
03-06 17:39:40.966: DEBUG/su(32134): 10123 oliver.ehrenmueller.dbadmin executing 0 /system/bin/sh using shell /system/bin/sh : sh
03-06 17:39:41.096: DEBUG/su(32139): su invoked.
03-06 17:39:41.106: DEBUG/su(32140): /dev/com.koushikdutta.superuser/.socket32138
03-06 17:39:41.997: DEBUG/su(32161): waiting for user
03-06 17:39:49.345: WARN/su(32181): request rejected (10123->0 /system/bin/sh)
03-06 17:39:49.545: DEBUG/su(32195): su invoked.
03-06 17:39:49.545: DEBUG/su(32196): /dev/com.koushikdutta.superuser/.socket32194
03-06 17:39:50.036: DEBUG/su(32212): waiting for user
03-06 17:39:53.569: DEBUG/su(32237): 10123 oliver.ehrenmueller.dbadmin executing 0 /system/bin/sh using shell /system/bin/sh : sh
03-06 17:39:57.113: DEBUG/su(32276): su invoked.
03-06 17:39:57.113: DEBUG/su(32277): /dev/com.koushikdutta.superuser/.socket32275
03-06 17:39:58.024: DEBUG/su(32289): waiting for user
03-06 17:40:02.859: DEBUG/su(32300): 10123 oliver.ehrenmueller.dbadmin executing 0 /system/bin/sh using shell /system/bin/sh : sh
03-06 17:40:02.989: DEBUG/su(32310): /dev/com.koushikdutta.superuser/.socket32307
03-06 17:40:02.989: DEBUG/su(32309): su invoked.
03-06 17:40:03.920: DEBUG/su(32335): waiting for user
03-06 17:40:07.835: DEBUG/su(32345): 10123 oliver.ehrenmueller.dbadmin executing 0 /system/bin/sh using shell /system/bin/sh : sh
03-06 17:40:08.115: DEBUG/su(32365): su invoked.
03-06 17:40:08.125: DEBUG/su(32366): /dev/com.koushikdutta.superuser/.socket32364
03-06 17:40:09.036: DEBUG/su(32387): waiting for user
03-06 17:40:12.950: WARN/su(32397): request rejected (10123->0 /system/bin/sh)
03-06 17:40:13.150: DEBUG/su(32412): su invoked.
03-06 17:40:13.150: DEBUG/su(32413): /dev/com.koushikdutta.superuser/.socket32411
03-06 17:40:14.091: DEBUG/su(32433): waiting for user
03-06 17:40:17.605: DEBUG/su(32498): 10123 oliver.ehrenmueller.dbadmin executing 0 /system/bin/sh using shell /system/bin/sh : sh
03-06 17:40:17.755: DEBUG/su(32510): su invoked.
03-06 17:40:17.755: DEBUG/su(32511): /dev/com.koushikdutta.superuser/.socket32509
03-06 17:40:18.746: DEBUG/su(32537): waiting for user
03-06 17:40:28.156: INFO/Superuser(31843): Result: 2 com.koushikdutta.superuser
03-06 17:40:28.166: DEBUG/su(32590): su invoked.
03-06 17:40:32.841: DEBUG/su(32612): 10125 com.koushikdutta.superuser executing 0 /system/bin/sh using shell /system/bin/sh : sh
03-06 17:40:32.851: DEBUG/su(32610): su invoked.
03-06 17:40:33.111: INFO/Superuser(31843): Result: 6 com.koushikdutta.superuser
03-06 17:40:33.111: DEBUG/su(32645): su invoked.
03-06 17:40:37.206: DEBUG/su(32663): su invoked.
03-06 17:40:37.216: DEBUG/su(32664): db allowed
03-06 17:40:37.216: DEBUG/su(32666): 10123 oliver.ehrenmueller.dbadmin executing 0 /system/bin/sh using shell /system/bin/sh : sh
03-06 17:40:38.888: DEBUG/su(32681): db allowed
03-06 17:40:38.888: DEBUG/su(32680): su invoked.
03-06 17:40:38.888: DEBUG/su(32683): 10123 oliver.ehrenmueller.dbadmin executing 0 /system/bin/sh using shell /system/bin/sh : sh
03-06 17:40:38.978: DEBUG/su(32690): db allowed
03-06 17:40:38.978: DEBUG/su(32689): su invoked.
03-06 17:40:38.998: DEBUG/su(32692): 10123 oliver.ehrenmueller.dbadmin executing 0 /system/bin/sh using shell /system/bin/sh : sh
03-06 17:40:40.319: DEBUG/su(32727): su invoked.
03-06 17:40:40.329: DEBUG/su(32728): db allowed
03-06 17:40:40.329: DEBUG/su(32730): 10123 oliver.ehrenmueller.dbadmin executing 0 /system/bin/sh using shell /system/bin/sh : sh
03-06 17:40:40.429: DEBUG/su(32736): su invoked.
03-06 17:40:40.429: DEBUG/su(32739): 10123 oliver.ehrenmueller.dbadmin executing 0 /system/bin/sh using shell /system/bin/sh : sh
03-06 17:40:40.429: DEBUG/su(32737): db allowed
03-06 17:40:48.758: WARN/su(308): request rejected (10123->0 /system/bin/sh)
03-06 17:51:56.331: INFO/Superuser(31843): Result: 6 com.koushikdutta.superuser
03-06 17:51:56.331: DEBUG/su(1279): su invoked.
03-06 17:52:02.507: DEBUG/su(1303): su invoked.
03-06 17:52:02.507: DEBUG/su(1306): 10123 oliver.ehrenmueller.dbadmin executing 0 /system/bin/sh using shell /system/bin/sh : sh
03-06 17:52:02.517: DEBUG/su(1304): db allowed

**Comment by koush** [comment]
Right, it shows a notification when su is requested. I'm wary of putting more info in that dialog, as it would start getting messy

**Comment by holde** [comment]
Well, as it doesn't work without updating (in this case) you could replace the dialog. Anyway, since I now know where I have to look I'm OK, but initially i was confused for a minute ;)

**Comment by koush** [comment]
Fixed with update.
