### ISSUE TITLE
Self-built app with different package id doesn't work

### ISSUE THREAD

**Issue by dalb8** [koush/Superuser#98]
I have tested many variations of this, but this is the latest situation. Flash superuser.zip via clockworkmod.com in recovery: all is well. 

Then, build the app with a different package id by using aapt in the build.xml with the same flags as in Superuser/Android.mk. Flash in recovery, restart and start Superuser: says the su is out dated. Install su and "Install: There was an error installing Superuser":`--------- beginning of /dev/log/main
D/SurfaceFlinger(  103): Screen about to return, flinger = 0x41b7caf0
V/Sensors (  280): handle : 14 en: 1 mEnabled:00000000
V/Sensors (  280): sensor state change what=14
V/Sensors (  280):  enabled_sensors: 16384 dmp_started: 0
V/Sensors (  280): Starting DMP
--------- beginning of /dev/log/system
I/WindowManager(  280): No lock screen!
I/        (  280): mpu3050_resume: Resuming to 0070
V/Sensors (  280): set fifo rate: 39 200000000
I/        (  280): mpu3050_suspend: suspending sensors to 0000
I/        (  280): mpu3050_suspend: Will resume next to 0070
I/MPL-ml  (  280): Actual ODR: 25 Hz
I/        (  280): mpu3050_resume: Resuming to 0070
V/Sensors (  280): set fifo rate: 13 66667000
I/        (  280): mpu3050_suspend: suspending sensors to 0000
I/        (  280): mpu3050_suspend: Will resume next to 0070
I/MPL-ml  (  280): Actual ODR: 25 Hz
I/        (  280): mpu3050_resume: Resuming to 0070
D/jp.co.qsdn.android.jinbei3d.setting.Prefs(  446): 2131034131 = getCameraMode()
D/dalvikvm(  280): GC_FOR_ALLOC freed 879K, 32% free 6346K/9287K, paused 63ms, total 63ms
E/PowerManagerService(  280): Excessive delay setting brightness: 209ms, mask=2
D/dalvikvm(  446): GC_CONCURRENT freed 1775K, 48% free 4401K/8451K, paused 8ms+3ms, total 49ms
V/tiny_hw (  106): out_write(0x40d7c540) opening PCM(0), card,dev: 0,0
D/dalvikvm(  486): GC_EXPLICIT freed 744K, 37% free 5327K/8451K, paused 2ms+3ms, total 32ms
I/ActivityManager(  280): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.gerry.superuser/com.koushikdutta.superuser.MainActivity u=0} from pid 486
D/dalvikvm(  280): GC_FOR_ALLOC freed 345K, 30% free 6517K/9287K, paused 44ms, total 44ms
I/dalvikvm-heap(  280): Grow heap (frag case) to 15.686MB for 1048592-byte allocation
D/jp.co.qsdn.android.jinbei3d.setting.Prefs(  446): 2131034131 = getCameraMode()
I/Superuser(  744): Result: 6 com.koushikdutta.superuser
W/System.err(  744): java.lang.Exception: unknown su
W/System.err(  744):    at com.koushikdutta.superuser.util.SuHelper.checkSu(SuHelper.java:17)
W/System.err(  744):    at com.koushikdutta.superuser.MainActivity$7.run(MainActivity.java:274)
D/su      (  995): su invoked. 
D/dalvikvm(  446): GC_CONCURRENT freed 1745K, 48% free 4401K/8451K, paused 3ms+3ms, total 24ms
D/libEGL  (  744): loaded /system/lib/egl/libEGL_tegra.so
D/libEGL  (  744): loaded /system/lib/egl/libGLESv1_CM_tegra.so
D/libEGL  (  744): loaded /system/lib/egl/libGLESv2_tegra.so
D/OpenGLRenderer(  744): Enabling debug mode 0
I/ActivityManager(  280): Displayed org.gerry.superuser/com.koushikdutta.superuser.MainActivity: +1s2ms
E/tiny_hw (  106): out_write(0x40d7c540) PCM(0) failed: -32
E/tiny_hw (  106): out_write(0x40d7c540) PCM(0) failed: -32
V/tiny_hw (  106): out_standby(0x40d7c540) closing PCM(0)
V/tiny_hw (  106): out_write(0x40d7c540) opening PCM(0), card,dev: 0,0
W/System.err(  744): java.lang.Exception: non zero result
W/System.err(  744):    at com.koushikdutta.superuser.MainActivity$3.run(MainActivity.java:181)
D/su      ( 1003): su invoked. 
E/su      ( 1005): stat /data/data/com.koushikdutta.superuser failed with 2: No such file or directory 
W/su      ( 1007): request rejected (10036->0 /system/bin/sh) 
D/AndroidRuntime( 1008): 
D/AndroidRuntime( 1008): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 1008): CheckJNI is OFF
D/dalvikvm( 1008): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 1008): Added shared lib libjavacore.so 0x0
D/dalvikvm( 1008): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 1008): Added shared lib libnativehelper.so 0x0
D/AndroidRuntime( 1006): 
D/AndroidRuntime( 1006): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 1006): CheckJNI is OFF
D/dalvikvm( 1006): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 1006): Added shared lib libjavacore.so 0x0
D/dalvikvm( 1006): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 1006): Added shared lib libnativehelper.so 0x0
D/AndroidRuntime( 1008): Calling main entry com.android.commands.am.Am
W/PackageManager(  280): Removing dangling preferred activity: ComponentInfo{com.android.browser/com.android.browser.BrowserActivity}
I/ActivityManager(  280): START {act=android.intent.action.VIEW dat=http://www.clockworkmod.com/superuser/install.html flg=0x10000000 cmp=android/com.android.internal.app.ResolverActivity u=0} from pid 1008
D/AndroidRuntime( 1008): Shutting down VM
D/AndroidRuntime( 1006): Calling main entry com.android.commands.am.Am
D/dalvikvm( 1008): GC_CONCURRENT freed 98K, 81% free 492K/2560K, paused 1ms+0ms, total 19ms
D/AndroidRuntime( 1006): Shutting down VM
I/AndroidRuntime( 1006): NOTE: attach of thread 'Binder_2' failed
D/dalvikvm( 1006): GC_CONCURRENT freed 100K, 81% free 499K/2560K, paused 1ms+0ms, total 6ms
D/dalvikvm(  280): GC_CONCURRENT freed 510K, 24% free 8140K/10695K, paused 4ms+5ms, total 72ms
I/ActivityManager(  280): Displayed android/com.android.internal.app.ResolverActivity: +177ms
E/tiny_hw (  106): out_write(0x40d7c540) PCM(0) failed: -32
E/tiny_hw (  106): out_write(0x40d7c540) PCM(0) failed: -32
E/tiny_hw (  106): out_write(0x40d7c540) PCM(0) failed: -32
E/tiny_hw (  106): out_write(0x40d7c540) PCM(0) failed: -32
V/tiny_hw (  106): out_standby(0x40d7c540) closing PCM(0)`

build.xml: `<target name="-package-resources" depends="-crunch">
               <exec executable="${aapt}" failonerror="true">
                        <arg value="package" />
                        <arg value="-f" />
                        <arg value="-M" />
                        <arg path="AndroidManifest.xml" />
                        <arg value="-A" />
                        <arg path="${asset.absolute.dir}" />
                        <arg value="-F" />
                        <arg path="${out.absolute.dir}/${resource.package.file.name}" />
                        <arg value="-I" />
                        <arg path="${android.jar}" />
                        <arg value="-S" />
                        <arg path="${resource.absolute.dir}" />
                        <arg value="-S" />
                        <arg path="${android.library.reference.1}/res" />
                        <arg value="--extra-packages" />
                        <arg value="com.koushikdutta.widgets" />
                        <arg value="--auto-add-overlay" />
                        <arg value="--rename-manifest-package" />
                        <arg value="org.gerry.superuser" />
                </exec>
   </target>
`

**Comment by koush** [comment]
you need to also change the REQUESTOR val in su.h

**Comment by dalb8** [comment]
Thanks: I should have thought to look at the code where it mentioned the package id. I now have: 
`// If --rename-manifest-package is used in AAPT, this
// must be changed to correspond to the new APK package name
// See the two Android.mk files for more details.
#ifndef REQUESTOR
#define REQUESTOR "org.gerry.superuser"
#endif
#ifndef REQUESTOR_PREFIX
#define REQUESTOR_PREFIX "org.gerry.superuser"
#endif`
but I effectively lose root (after getting "superuser installed successfully"):

`D/jp.co.qsdn.android.jinbei3d.setting.Prefs(  432): 2131034131 = getCameraMode()
I/ActivityManager(  281): Displayed org.ntpsync/.ui.BaseActivity: +205ms
D/su      ( 1261): su invoked.
D/su      ( 1262): /dev/org.gerry.superuser/.socket1260
D/AndroidRuntime( 1263):
D/AndroidRuntime( 1263): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 1263): CheckJNI is OFF
D/dalvikvm( 1263): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 1263): Added shared lib libjavacore.so 0x0
D/dalvikvm( 1263): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 1263): Added shared lib libnativehelper.so 0x0
D/AndroidRuntime( 1263): Calling main entry com.android.commands.am.Am
D/AndroidRuntime( 1263): Shutting down VM
I/ActivityManager(  281): START {flg=0x10000000 cmp=org.gerry.superuser/.RequestActivity (has extras) u=0} from pid 1263
D/dalvikvm( 1263): GC_CONCURRENT freed 100K, 81% free 496K/2560K, paused 1ms+0ms, total 5ms
V/tiny_hw (  106): out_standby(0x41f94a88) closing PCM(0)
D/dalvikvm(  852): GC_CONCURRENT freed 1779K, 63% free 3184K/8451K, paused 5ms+3ms, total 45ms
E/NTPSync ( 1185): Android is not rooted or root access was denied!
E/NTPSync ( 1185): org.rootcommands.util.RootAccessDeniedException: stdout line is null! Access was denied or this executeable is not a shell!`

**Comment by koush** [comment]
dont set requestor prefix.

**Comment by dalb8** [comment]
Thanks for your help. The latest apk is now on F-Droid.org. The only other changes was to use GCC 4.6 (temporary) and remove the references in AboutFragment to Google Play and the other proprietary apps. We mention your Google Play page in the description if they need a flashable zip.
