### ISSUE TITLE
Add the option to remove the PIN

### ISSUE THREAD

**Issue by zanza00** [koush/Superuser#99]
Right now you can only change the PIN to a new one once is set, but you can't remove it.

**Comment by Fifteen15Studios** [comment]
You can remove it by just pressing OK when entering a new pin, but that is not immediately obvious to the user.

**Comment by koush** [comment]
@havens1515 is correct. I'll see about how I can add a remove pin option.

**Comment by koush** [comment]
Clicking on the pin protection option while a pin is set will now unset it. The user can change the pin by clicking it again when it is unset.
